### ISSUE TITLE
derive Uninhabited

### ISSUE THREAD

**Issue by dvc94ch** [stefan-hoeck/idris2-sop#3]
that one is quite a pain to implement if you have a few variants

**Comment by stefan-hoeck** [comment]
Could you draft a quick example, how you'd do that using the SOP approach? Because to the best of my knowledge, `Uninhabited` usually talks about families of types, while in this library, we can only handle parameterized data types.

**Comment by dvc94ch** [comment]
Maybe needs a separate library then, haven't put much thought into it. Just remember writing 250loc implementing uninhabited and seemed like this library was doing something similar.
